-- Apaga 12 tabelas

DROP TABLE log_prof;

DROP TABLE log_cliente;

DROP TABLE habilidade_prof;

DROP TABLE idioma_prof;

DROP TABLE regiao_prof;

DROP TABLE prof;

DROP TABLE curso;

DROP TABLE regiao;

DROP TABLE idiomas;

DROP TABLE habilidades;

DROP TABLE cliente;

DROP TABLE campus;

-- Apaga 9 sequences

DROP SEQUENCE scampus;

DROP SEQUENCE scliente;

DROP SEQUENCE shabilidades;

DROP SEQUENCE sregiao;

DROP SEQUENCE sidiomas;

DROP SEQUENCE scurso;

DROP SEQUENCE sprof;

DROP SEQUENCE slog_cliente;

DROP SEQUENCE slog_prof;

-- FIM DO ARQUIVO DROP